Avoid issues if no default list is found
wikimedia/webextension-readinglists pull request #8
Opened 2018-04-26 17:37 UTC by berndsi

plus some minor cleanup

2018-04-26 23:57 UTC, mdholloway requested changes

2018-04-26 23:57 UTC, mdholloway commented on popup.js
> -        document.getElementById('loginButton').onclick = (element) => showLoginPage(url, title);
Does the onclick listener still work (on both browsers) with this change?

2018-04-26 23:57 UTC, mdholloway commented on popup.js
> -        document.getElementById('loginButton').onclick = (element) => showLoginPage(url, title);
Okay, I checked and it does. There's another instance of the same that could come out on line 104 as well.

2018-04-27 03:52 UTC, berndsi commented on popup.js
> -        document.getElementById('loginButton').onclick = (element) => showLoginPage(url, title);
Not sure what you mean at line 104.

2018-05-07 13:55 UTC, mdholloway commented on popup.js
> -        document.getElementById('loginButton').onclick = (element) => showLoginPage(url, title);
Oops, sorry, I'm looking at code added locally in a later commit.

2018-05-07 13:56 UTC, mdholloway approved these changes

2018-05-07 13:56 UTC, merged